services:
  backend:
    build:
      context: .
    container_name: fastapi-app
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 3600:3500
    networks:
      - backnet
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    ports:
      - '6379:6379'

  mongo:
    image: mongo
    container_name: fastapi-app-db
    networks:
      - backnet

networks:
  backnet:
  frontnet:
