services:
  backend:
    build:
      context: .
    container_name: fastapi-app
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 3600:3500
    networks:
      - backnet
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    container_name: fastapi-app-redis
    ports:
      - 6379:6379
    networks:
      - backnet

  mongo:
    image: mongo
    container_name: fastapi-app-db
    networks:
      - backnet

networks:
  backnet:
  frontnet:
